import { FC } from "react";

const Home: FC = () => {
  return (
    <div>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
      <h1>sdasdsasadsadsad</h1>
    </div>
  );
};

export default Home;
